spring.application.name: webflux1
spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:mysql://localhost:3307/fastsns
    username: root
    password: user
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    root: info
